FROM python:3.14-slim-trixie

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

RUN apt update && apt install -y ffmpeg

RUN pip install pipenv

WORKDIR /app
COPY Pipfile .

RUN pipenv install --system --deploy --ignore-pipfile

COPY . .

RUN adduser --disabled-password --gecos "" appuser && chown -R appuser /app
USER appuser

CMD [ "python", "main.py" ]